import sqlite3
conn = sqlite3.connect('WIKI.sqlite')
cursor = conn.cursor()
cursor.execute("CREATE TABLE extra(name text,min real,max real)")
conn.commit()
cursor.execute("SELECT min(score1),max(score1),min(score2),max(score2),min(score3),max(score3),min(score4),max(score4) from Wiki")
line=cursor.fetchone()
cursor.execute("INSERT INTO extra VALUES(?,?,?)",("score1",line[0],line[1]))
cursor.execute("INSERT INTO extra VALUES(?,?,?)",("score2",line[2],line[3]))
cursor.execute("INSERT INTO extra VALUES(?,?,?)",("score3",line[4],line[5]))
cursor.execute("INSERT INTO extra VALUES(?,?,?)",("score4",line[6],line[7]))
conn.commit()
cursor.execute("CREATE INDEX cluster_index on wiki(cluster_id)")
conn.commit()